### ISSUE TITLE
Running unit tests on a dependency unloads that dependency.

### ISSUE THREAD

**Issue by Thom1729** [SublimeText/UnitTesting#145]
1. Open any `sublime_lib` test file.
2. Run `UnitTesting: Test Current File`. (Tests succeed.)
3. Run a command from another package that imports `sublime_lib`.
4. An error is raised because something is `None` that shouldn't be.
5. Reload that other package manually.
6. It works.

The cause is that `reload_plugin` doesn't reload dependencies. If I force `reload_missing` to run, it does reload the unloaded dependency files.

**Comment by randy3k** [comment]
Why the dependencies are unloaded at the first place? It has a prefix the same as the package being tested?

**Comment by Thom1729** [comment]
I'm testing a dependency. We use `UnitTesting` as the test framework for `sublime_lib`. So `sublime_lib` *is* the “package being tested”, but of course it's not actually a package so things get weird.

**Comment by Thom1729** [comment]
To be honest, I don't really understand what the whole reload system is doing and why. I'd really like to fix it up.

**Comment by randy3k** [comment]
It is to make sure of 100% coverage. Loading the module is a part of the coverage.

**Comment by Thom1729** [comment]
Maybe it just doesn't make sense to do that for a dependency, then. I've added `"reload_package_on_testing": false` to `unittesting.json`, and that seems to have fixed it.

If we want to make reloading dependencies work, I guess we'd have to reload all dependent packages. This is probably an issue for [AutomaticPackageReloader](https://github.com/randy3k/AutomaticPackageReloader).

**Comment by Thom1729** [comment]
https://github.com/randy3k/AutomaticPackageReloader/issues/12

**Comment by evandrocoan** [comment]
Hi @Thom1729, thanks for reporting this and sharing a work around.

I do not think my issue is exactly with my dependency not being loaded back, but with the fact it is deleted or unloaded before before running the Unit Tests. This is a major problem for my dependency [debugtools](https://github.com/evandrocoan/debugtools) because it have a singleton module which cannot be unloaded, as it replaces/monkey patch `sys.stderr` and `sys.stdout` (on Sublime Text start up, i.e., when the first package which uses the dependency is loaded), and as soon as I run the unit tests command, no Unit Test pass and Sublime Text console dies because `sys.stderr` and `sys.stdout` are replaced with `None` after my dependency is unloaded/deleted.

Now, all my Unit Tests fail like this and the Sublime Text console dies with no new output from any thing:
```
======================================================================
ERROR: test_createStdoutHandler (testing.utilities_unit_tests.UtilitiesUnitTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\Packages\debugtools\tests\testing\utilities_unit_tests.py", line 203, in test_createStdoutHandler
    utilities._create_stdout_handler()
  File "F:\Packages\debugtools\all\debug_tools\utilities.py", line 623, in _create_stdout_handler
    sys.stderr.write( '\nCreating the `stdout_replacement.py` file!\n' )
  File "F:\Packages\debugtools\tests\testing\std_capture.py", line 85, in write
    self._std_original.write( *args, **kwargs )
  File "F:\Packages\UnitTesting\unittesting\utils\stdio_splitter.py", line 7, in write
    self.io.write(data)
TypeError: 'NoneType' object is not callable
```

Indeed, using `"reload_package_on_testing": false` on `unittesting.json` fixes the issue and all my Unit Tests starts passing again, once Sublime Text is restarted. This problem started after a commit on this package, not after an update on AutomaticPackageReloader. After reverting both packages back to their latest version on October/2017, when everything was working fine with my dependency and performing a binary search, i.e., checkout new commits since October/2017 up to today when it stopped working, I manage to isolate the problem to the following commit:
1. UnitTesting@https://github.com/SublimeText/UnitTesting/commit/38f90ddf5bb0545cdd7232f1731c435d51886ac0 update reloader code

On the commit just before it, everything is working fine, but after applying this commit, my dependency breaks with this issue. The commit title seems very misleading, because after looking in to its contents, what it seems to be doing is implementing the reloader code for dependencies.

**Comment by Thom1729** [comment]
UnitTesting and AutomaticPackageReloader use the same reloading code. AutomaticPackageReloader was improved to handle dependencies, and now UnitTesting handles them as well.

I'm not sure that there is any sensible way for a general-purpose reloader to handle dependencies that patch shared global state on load. `"reload_package_on_testing": false` seems like an appropriate solution here. On the other hand, the vast majority of dependencies should work fine.

**Comment by Thom1729** [comment]
I'm closing this issue because the dependency reloading changes have been integrated.

**Comment by evandrocoan** [comment]
And integrating the dependency reload code fixed this issue?
