### ISSUE TITLE
Travis CI errors

### ISSUE THREAD

**Issue by gerardroche** [SublimeText/UnitTesting#74]
I'm getting CI errors on travis, what changed?

```
...
sublime_text_3/Icon/48x48/sublime-text.png
sublime_text_3/Icon/256x256/
sublime_text_3/Icon/256x256/sublime-text.png
sublime_text_3/sublime.py
sublime_text_3/sublime_plugin.py

travis_time:end:24f9deb4:start=1514012490463751222,finish=1514012494801732430,duration=4337981208
[0K
[31;1mThe command "sh travis.sh bootstrap" failed and exited with 1 during .[0m

Your build has been stopped.
```

https://travis-ci.org/NeoVintageous/NeoVintageous/builds/320570276

https://api.travis-ci.org/v3/job/320570277/log.txt

**Comment by randy3k** [comment]
You forgot to run Xvfb on Linux builds.
https://github.com/randy3k/UnitTesting-example/blob/master/.travis.yml#L21-L25

It was not needed because there was a safety net but the net was just removed https://github.com/SublimeText/UnitTesting/commit/9a152e1797c9fe0b2965874a7ee940384881d0cb#diff-c79de8dc48648dbdee7fa6985d9951eaL12

**Comment by gerardroche** [comment]
The circle ci changes 

https://github.com/SublimeText/UnitTesting/commit/9a152e1797c9fe0b2965874a7ee940384881d0cb

Looking at the example linked from the readme: https://github.com/randy3k/UnitTesting-example/blob/master/.travis.yml

It looks like some things need to be defined in the travis configs, things like: 

```
    # enable gui, see https://docs.travis-ci.com/user/gui-and-headless-browsers
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
fi
```

**Comment by gerardroche** [comment]
Yeah, can we add that stuff back to the unittesting scripts? It's nice not having to add that to the configs.

**Comment by randy3k** [comment]
Putting 
```
sh -e /etc/init.d/xvfb start;
```
in Travis config is the correct and the [official](https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI) way to run Xvfb.

If we put it in the script, we have to check if Xvfb is running for every GUI execution (the env variable `DISPLAY` does not work for this purpose because it is only defined in the script, Travis doesn't have any idea about it).

As there is a [plan](https://github.com/SublimeText/UnitTesting/issues/71) to refactor the deploy scripts of CI, I think it's time to make it the right way.

**Comment by randy3k** [comment]
But it may be useful to catch the error and link users to this issue.

**Comment by gerardroche** [comment]
+1 for deprecating it, add a link to the issue. 

Also, I see that the url has changed from randy2k to SublimeText. Maybe add bold notice at the top of readme to notify users of the change.

**Comment by randy3k** [comment]
I have just added a message https://github.com/SublimeText/UnitTesting/blob/65fd0ccb9d93605772bc3e580656aff07199d45d/sbin/travis.sh#L12-L16

**Comment by gerardroche** [comment]
In the example there is some install code in the after_success section. Is there are specific reason for this. I generally move that to *before* bootstrap in the install section e.g.:

```
install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            pip install flake8;
            pip install flake8-docstrings;
            pip install python-coveralls;
      elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
            brew update;
            brew install python3;
            pip3 install flake8;
            pip3 install flake8-docstrings;
            pip3 install python-coveralls;
      fi
    - sh travis.sh bootstrap
```

**Comment by randy3k** [comment]
Added a note about the repo relocation.
https://github.com/SublimeText/UnitTesting#unittesting

> Is there are specific reason for this?

`python-coveralls` is only needed when the build successes. It is not necessary to install time if the build fails. Thus it will shorten the notification time.
